import type { Role } from '../domain'

export type MvpSettings = {
  revealRoleOnDeath: boolean
  seerResult: 'TEAM_ALIGNMENT'
  voteTie: 'REVOTE_ONCE'
  witchCanSelfHeal: boolean
  witchCanUseBothPotions: boolean
  witchCanSelfPoison: boolean
}

export const MVP_ROLE_COMPOSITIONS = {
  5: ['WEREWOLF', 'SEER', 'VILLAGER', 'VILLAGER', 'VILLAGER'],
  6: ['WEREWOLF', 'SEER', 'WITCH', 'VILLAGER', 'VILLAGER', 'VILLAGER'],
  7: [
    'WEREWOLF',
    'WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'VILLAGER',
    'VILLAGER',
  ],
  8: [
    'WEREWOLF',
    'WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
  ],
  9: [
    'WEREWOLF',
    'WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
  ],
  10: [
    'WEREWOLF',
    'WEREWOLF',
    'WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
  ],
  11: [
    'WEREWOLF',
    'WEREWOLF',
    'WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
  ],
  12: [
    'WEREWOLF',
    'WEREWOLF',
    'WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
  ],
  13: [
    'WEREWOLF',
    'WEREWOLF',
    'ALPHA_WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
  ],
  14: [
    'WEREWOLF',
    'WEREWOLF',
    'WEREWOLF',
    'ALPHA_WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
  ],
  15: [
    'WEREWOLF',
    'WEREWOLF',
    'WEREWOLF',
    'ALPHA_WEREWOLF',
    'SEER',
    'WITCH',
    'PROTECTOR',
    'HUNTER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
    'VILLAGER',
  ],
} as const satisfies Record<number, readonly Role[]>

export const MVP_SETTINGS = {
  revealRoleOnDeath: false,
  seerResult: 'TEAM_ALIGNMENT',
  voteTie: 'REVOTE_ONCE',
  witchCanSelfHeal: true,
  witchCanUseBothPotions: true,
  witchCanSelfPoison: false,
} as const satisfies MvpSettings
