/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as GameRouteRouteImport } from './routes/game/route'
import { Route as LobbyRouteRouteImport } from './routes/lobby/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homePlayRouteImport } from './routes/(home)/play'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRouteRoute = GameRouteRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRouteRoute = LobbyRouteRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homePlayRoute = homePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => homeRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/game': typeof GameRouteRoute
  '/lobby': typeof LobbyRouteRoute
  '/play': typeof homePlayRoute
  '/': typeof homeIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/game': typeof GameRouteRoute
  '/lobby': typeof LobbyRouteRoute
  '/play': typeof homePlayRoute
  '/': typeof homeIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/game': typeof GameRouteRoute
  '/lobby': typeof LobbyRouteRoute
  '/(home)/play': typeof homePlayRoute
  '/(home)/': typeof homeIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/game' | '/lobby' | '/play' | '/' | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/game' | '/lobby' | '/play' | '/' | '/api/rpc/$'
  id:
    | '__root__'
    | '/(home)'
    | '/game'
    | '/lobby'
    | '/(home)/play'
    | '/(home)/'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  GameRouteRoute: typeof GameRouteRoute
  LobbyRouteRoute: typeof LobbyRouteRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/play': {
      id: '/(home)/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof homePlayRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface homeRouteRouteChildren {
  homePlayRoute: typeof homePlayRoute
  homeIndexRoute: typeof homeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homePlayRoute: homePlayRoute,
  homeIndexRoute: homeIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  GameRouteRoute: GameRouteRoute,
  LobbyRouteRoute: LobbyRouteRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
